font_family      family="Fira Code" style=Light
bold_font        family="Fira Code" style=Regular
italic_font      family="Fira Code" style=Light
bold_italic_font family="Fira Code" style=Regular

font_size 18.0

cursor_blink_interval 0
macos_option_as_alt yes
hide_window_decorations yes
placement_strategy top-left

