(require :user/plugins/colorscheme)
(require :user/plugins/telescope)
(require :user/plugins/treesitter)
(require :user/plugins/lsp)
(require :user/plugins/conjure)
(require :user/plugins/gitsigns)
(require :user/plugins/comment)
